In [ ]:
import numpy as np

class Perceptron(object):

    def __init__(self,input_size,lr=1,epochs=10):
        self.W = np.zeros(input_size+1)
        # add one for bias
        self.epochs = epochs
        self.lr = lr
           
    def activation_fn(self,x):
        return 1 if x >= 0 else 0
    
    def predict(self,x):
        x = np.insert(x,0,1)
        z = self.W.T.dot(x)
        a = self.activation_fn(z)
        return a
    
    def fit(self,X,d):
        for _ in range(self.epochs):
            for i in range(d.shape[0]):
                y = self.predict(X[i])
                e = d[i] - y
                self.W = self.W + self.lr * e * np.insert(X[i],0,1)

In [3]:
X = np.array([
        [0,0],
        [0,1],
        [1,0],
        [1,1]])

In [4]:
d = np.array([0,0,0,1])

In [5]:
X

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [6]:
d

array([0, 0, 0, 1])

In [7]:
perceptron = Perceptron(input_size=2)

In [8]:
perceptron.W

array([0., 0., 0.])

In [9]:
perceptron.fit(X,d)

In [10]:
perceptron.W

array([-3.,  2.,  1.])

In [11]:
print(perceptron.W)

[-3.  2.  1.]


In [12]:
perceptron.predict(np.asarray([1,0]))

0

In [13]:
mp = Perceptron(5)
x = np.asarray([1,1,0,0,0])
mp.predict(x)

1

In [14]:
mp.activation_fn(10)

1

In [15]:
mp.W

array([0., 0., 0., 0., 0., 0.])

<Perceptron>

    Yapay sinir ağı modelinin en küçük parçası olan perceptron'da y = W.x+b lineer fonksiyonuyla tanımlanır.  
x girdi değerimiz, örneğin kedi resimlerini tanıyorsak kedi resmine ait matrisi, y ise bu resmin kediye ne kadar benzediğine dair skoru verir. Parametrelerimiz olan W ağırlık ve b bias değerlerini bu çıktı skorunu iyileştirmek için kullanılır. Bu anlamda çok katmanlı yapay sinir ağlarında ya da derin öğrenme de yaptığımız temel şey modelimiz için en iyi skoru verecek w ve b parametre değerlerini hesaplamaktır.
    
  Derin bir sinir ağı oluşturmak için temel bir yapı taşı olarak hizmet eder. Temel olarak, veri setini tek bir satır kullanarak iki kategoride sınıflandırabiliyorsanız, bu problem doğrusal olarak ayrılabilir olarak adlandırılır. Doğrusal olmayan ayrılabilir problemler de vardır. Bu problemlerde veri seti çoklu sınıflar içerir ve bunları kendi sınıflarına ayırmak için doğrusal olmayan bir çizgi gerektirir.
Doğrusal olarak ayrılabilir bir problemin grafiğini çizerek ve doğrusal olmayan problemli veri setini çizerek, ikisi arasındaki fark şu şekildedir: 

        1) Perceptron class tanımında var olan fonksiyonları kısaca tanıtınız.

<init fonksiyonu>
Bir programı çağırdığınızda değişkenler başlatılmaz. Yani, bu kodu kullanarak programındaki tüm değişkenleri açıkça başlatırız. Bununla beraber bir perceptron yani Algılayıcı oluşturmuş oluruz. Weight yani “ağırlık” vektörünü oluşturmamız gerekir bu işlem için bir kullanıcıdan girdi alırız. W.x çarpımından oluşturulan lineer doğruyu öteleyerek daha iyi çözecek konuma getirmek için bias değerini ekliyoruz. Dışarıdan değişitirilebilir olarak 2 parametre ekledik. Öğrenme oranını ve devir sayısı değiştirilebilirlerdir.

<activation_fn fonksiyonu>
Çıktılar aktivasyon fonksiyonlarıyla non-lineer hale getirilebilmektedir. Aktivasyon fonksiyonumuz eşik değeri belirledikten sonra,
eğer girdi 0 dan büyük veya eşitse  1 , değilse 0 döndürüyoruz. 
Böylelikle gelen girdi için çıkacak çıktıyı bulmuş oluyoruz.

<predict fonksiyonu>
Bu fonksiyon Tahmin fonksiyonudur. Perceptron yardımıyla girdiyi çalıştırıyoruz. Bunun sonucunda çıktı döndürmesi için yazılması gereken ve sonucunun bize verildiği fonksiyondur. giriş vektörüne ekledik. İç çarpımı hesapladık ve aktivasyon fonksiyonunu kullandık. Makineye bunu öğrettikten sonra sonuç tahmin edilir.

<fit fonksiyonu>
Makineyi eğittiğimiz, öğrettiğimiz fonksiyondur.

        2) XOR için verileri değiştirip çalışmasınızı gözlemleyiniz.

    Tek katmanlı perceptron’un birçok Bool fonksiyonunu öğrenebildiği gösterildi. Fakat perceptron’un XOR fonksiyonunu öğrenemeyeceğini gösterdi. 
Bir perceptrona mazur bırakıp outputunu alıprız. Bir başka perceptrona göndeririz. Önce 2 ye ayırıp sorunlu olan tarafı tekrar bir perceptrona maruz bırakıp tamamen çözüm sağlayabilriz. 2 perceptrona maruz bırakılıan sorun çözüldüğünde artık MLP ortaya çıkmış olur. Yani ihtiyaç olduğu kadar perceptron uygulanarak sorun çözülebilir.

        3) Bu class ile dersimize kayıtlı 40 öğrenci için imza tanıması yapılırsa X ve d değerlerini ne olur, predict fonksiyonu nasıl kullanılır açıklayınız.

    2 input değerlerimiz vardır. X değerleri input ve d değerleri ise output'u temsil etmektedir. Bunlar Yükseklik - Genişlik değerleridir. Bunun sonucunda X değeri 40 adet dizi tutar bunlar imzaları tutacaktır. d değeri ise 40 elemanlıdır. Bu değerlerin her biri X dizisinde bulunan imzanın hangi öğrenciye ait olduğunu gösterir. Her bir sütununda bir kişiye ait imza resmi olmak üzere (100*100*3,40) lık matrix bizim verimiz olacaktır. 
Sıradaki işlem predict fonsiyonunu kullanıp imzanın kime ait olduğunu bulmaktır. Bunun için predict fonsiyonua input olarak öğrenci imzası verilir. Predict fonksiyonu sonuç olarak imzanın hangi öğrenciye ait olduğunu çıktı olarak verir. 

        4)Bu modelin hatası nasıl elde edilir, kendi çözümünüzü/ yorumunuzu yazınız.

    Yaptığım araştırmlar sonucunda birkaç hata çözümlemesi ile karşılaştım.
** TensorFlow, ardışık yinelemelerde kaybı en aza indirmek için her bir değişkeni (ağırlık ve sapma) yavaşça değiştiren optimize ediciler sağlar. En basit iyileştirici, hata gidericidir. 
** Aynı zamanda hatayı hesaplamak için çapraz entropi(cross entropy) kullanılabilir.  Zamanın her birinde, maliyet hesaplanır ve bu maliyete bağlı olarak optimizatör, hatayı en aza indirmek için ağırlık ve önyargı değişkenlerini değiştirir.
